# Generated by Django 4.0.1 on 2022-01-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isImage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='message_image',
            field=models.ImageField(blank=True, null=True, upload_to='messages/'),
        ),
    ]
