# Generated by Django 4.0.2 on 2022-02-11 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-request_time', 'room'], 'verbose_name': 'Join request'},
        ),
    ]
