# Generated by Django 4.0.1 on 2022-01-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_message_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_image',
            field=models.ImageField(blank=True, default='messages/giphy.gif', null=True, upload_to='messages/'),
        ),
    ]
