# Generated by Django 4.0.1 on 2022-02-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_message_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_image',
            field=models.ImageField(blank=True, default='messages/default.jpg', null=True, upload_to='messages/'),
        ),
    ]
